# Generated by Django 2.2.6 on 2019-10-15 08:44

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import tram.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetnummer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('beschrijving', models.CharField(max_length=70, null=True)),
                ('bevat_logo', models.BooleanField()),
                ('ip_adres', models.GenericIPAddressField(null=True)),
                ('logo_online', models.BooleanField()),
                ('telefoonnummer', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguratieLijst',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=50)),
                ('config', djongo.models.fields.ArrayModelField(model_container=tram.models.Configuratie)),
            ],
        ),
        migrations.CreateModel(
            name='Urgentieniveau',
            fields=[
                ('niveau', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('beschrijving', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogoMelding',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('waarde', models.IntegerField()),
                ('tijdstip', models.DateTimeField(auto_now=True)),
                ('assetnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Configuratie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputnummer', models.SmallIntegerField()),
                ('signaaltype', models.CharField(choices=[('analoog', 'Analoog'), ('pulse', 'Dig. pulse'), ('digitaal', 'Digitaal')], default='digitaal', max_length=15)),
                ('beschrijving', models.CharField(max_length=50, null=True)),
                ('urgentieniveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Urgentieniveau')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='configuratie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.ConfiguratieLijst'),
        ),
    ]
