# Generated by Django 2.2.7 on 2020-02-18 11:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import tram.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsoluteData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('storing_beschrijving', djongo.models.fields.ListField(default=[], editable=False)),
                ('druk_a1', models.IntegerField()),
                ('druk_a2', models.IntegerField()),
                ('druk_b1', models.IntegerField()),
                ('druk_b2', models.IntegerField()),
                ('kracht_a', models.IntegerField()),
                ('kracht_b', models.IntegerField()),
                ('omloop_a', models.IntegerField()),
                ('omloop_b', models.IntegerField()),
                ('tijdstip', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'absolute data',
                'get_latest_by': 'tijdstip',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetnummer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('beschrijving', models.CharField(max_length=70, null=True)),
                ('ip_adres_logo', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_adres_modem', models.GenericIPAddressField(blank=True, null=True)),
                ('pollbaar', models.BooleanField(default=False)),
                ('weging', models.IntegerField(default=1)),
                ('variant', models.CharField(max_length=200)),
                ('link_fotos', models.CharField(max_length=200)),
                ('link_tekeningen', models.CharField(max_length=200)),
                ('lat_coordinaat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon_coordinaat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Configuratie',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('naam', models.CharField(max_length=50)),
                ('config', djongo.models.fields.ArrayField(model_container=tram.models.ConfiguratieElement)),
            ],
        ),
        migrations.CreateModel(
            name='SmsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontvangen', models.DateTimeField()),
                ('modem', models.CharField(default='', max_length=10)),
                ('telnummer', models.CharField(max_length=15, null=True)),
                ('storing', models.CharField(max_length=100, null=True)),
                ('smsc', models.CharField(max_length=15, null=True)),
                ('udh', models.BooleanField()),
                ('inputnummer', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('alphabet', models.CharField(max_length=15, null=True)),
                ('sent', models.DateTimeField()),
                ('sim', models.CharField(max_length=10, null=True)),
                ('asset', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'sms data',
                'get_latest_by': 'ontvangen',
            },
        ),
        migrations.CreateModel(
            name='Urgentieniveau',
            fields=[
                ('niveau', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('beschrijving', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gezien', models.BooleanField()),
                ('actief', models.BooleanField()),
                ('bericht', models.CharField(default='', max_length=100)),
                ('som', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=1)),
                ('assetnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Asset')),
                ('laatste_data', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tram.AbsoluteData')),
            ],
            options={
                'verbose_name_plural': 'storingen',
            },
        ),
        migrations.CreateModel(
            name='LogoData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('storing', models.IntegerField()),
                ('druk_a1', models.IntegerField()),
                ('druk_a2', models.IntegerField()),
                ('druk_b1', models.IntegerField()),
                ('druk_b2', models.IntegerField()),
                ('kracht_a', models.IntegerField()),
                ('kracht_b', models.IntegerField()),
                ('omloop_a', models.BigIntegerField()),
                ('omloop_b', models.BigIntegerField()),
                ('tijdstip', models.DateTimeField(auto_now=True)),
                ('assetnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Asset')),
            ],
            options={
                'verbose_name_plural': 'logo data',
                'get_latest_by': 'tijdstip',
            },
        ),
        migrations.CreateModel(
            name='ConfiguratieElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputnummer', models.SmallIntegerField()),
                ('beschrijving', models.CharField(max_length=100, null=True)),
                ('timeout', models.IntegerField(default=24)),
                ('urgentieniveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Urgentieniveau')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='configuratie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.Configuratie'),
        ),
        migrations.AddField(
            model_name='absolutedata',
            name='assetnummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Asset'),
        ),
    ]
