# Generated by Django 2.2.6 on 2019-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logomelding',
            old_name='waarde',
            new_name='druk_a1',
        ),
        migrations.AddField(
            model_name='logomelding',
            name='druk_a2',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='druk_b1',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='druk_b2',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='kracht_a',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='kracht_b',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='omloop_a',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='omloop_b',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logomelding',
            name='storing',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
