# Generated by Django 2.2.7 on 2020-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuratie',
            name='config',
        ),
        migrations.AddField(
            model_name='configuratie',
            name='config',
            field=models.ManyToManyField(to='tram.ConfiguratieElement'),
        ),
    ]
