# Generated by Django 2.2.6 on 2019-11-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='aantal_omplopen',
            new_name='aantal_omlopen',
        ),
    ]
