# Generated by Django 2.2.6 on 2019-10-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0002_auto_20191017_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomelding',
            name='druk_a1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='druk_a2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='druk_b1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='druk_b2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='kracht_a',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='kracht_b',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='omloop_a',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='omloop_b',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='storing',
            field=models.CharField(max_length=10),
        ),
    ]
