# Generated by Django 2.2.7 on 2020-03-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0002_auto_20200306_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuratie',
            name='config',
        ),
        migrations.AddField(
            model_name='configuratieelement',
            name='configuratie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='tram.Configuratie'),
            preserve_default=False,
        ),
    ]
