# Generated by Django 2.2.6 on 2019-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0002_auto_20191104_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='disconnections',
            field=models.IntegerField(default=0),
        ),
    ]
