# Generated by Django 2.2.7 on 2020-03-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0003_auto_20200309_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='laatste_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tram.AbsoluteData'),
        ),
    ]
