# Generated by Django 2.2.6 on 2019-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0003_auto_20191021_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomelding',
            name='druk_a1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='druk_a2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='druk_b1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='druk_b2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='kracht_a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='kracht_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='omloop_a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='omloop_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='logomelding',
            name='storing',
            field=models.IntegerField(),
        ),
    ]
