# Generated by Django 2.2.6 on 2019-11-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0004_auto_20191105_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='laatste_polling',
            new_name='laatste_data',
        ),
    ]
