# Generated by Django 2.2.6 on 2019-11-07 11:31

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0005_auto_20191105_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storing',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('gezien', models.BooleanField()),
                ('actief', models.BooleanField()),
                ('score', models.IntegerField()),
                ('assetnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Asset')),
            ],
        ),
    ]
