# Generated by Django 2.2.7 on 2020-03-11 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0005_auto_20200309_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='laatste_logo_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tram.LogoData'),
        ),
    ]
