# Generated by Django 2.2.6 on 2019-11-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0006_storing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absolutedata',
            name='storing',
        ),
    ]
