# Generated by Django 2.2.7 on 2020-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0006_asset_laatste_logo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storing',
            name='laatste_data',
        ),
        migrations.AddField(
            model_name='storing',
            name='data',
            field=models.ManyToManyField(to='tram.AbsoluteData'),
        ),
    ]
