# Generated by Django 2.2.7 on 2020-03-11 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0007_auto_20200311_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='laatste_logo_data',
        ),
        migrations.AddField(
            model_name='absolutedata',
            name='omloop_a_toegevoegd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absolutedata',
            name='omloop_b_toegevoegd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='druk_a1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='druk_a2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='druk_b1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='druk_b2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='kracht_a',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='kracht_b',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='omloop_a',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='omloop_b',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='storing_beschrijving',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='absolutedata',
            name='storing_beschrijving',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='LogoData',
        ),
    ]
