# Generated by Django 2.2.6 on 2019-11-07 11:54

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0007_remove_absolutedata_storing'),
    ]

    operations = [
        migrations.AddField(
            model_name='absolutedata',
            name='storing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.Storing'),
        ),
        migrations.AddField(
            model_name='absolutedata',
            name='storing_beschrijving',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
