# Generated by Django 2.2.7 on 2020-03-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0008_auto_20200311_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storing',
            name='data',
        ),
        migrations.AddField(
            model_name='storing',
            name='laatste_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tram.AbsoluteData'),
        ),
    ]
