# Generated by Django 2.2.6 on 2019-11-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0008_auto_20191107_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absolutedata',
            name='storing',
        ),
        migrations.DeleteModel(
            name='Storing',
        ),
    ]
