# Generated by Django 2.2.7 on 2020-03-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0009_auto_20200324_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='gem_dag_druk_a1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_dag_druk_a2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_dag_druk_b1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_dag_druk_b2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_dag_omloop_a_freq',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_dag_omloop_b_freq',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_maand_druk_a1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_maand_druk_a2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_maand_druk_b1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_maand_druk_b2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_maand_omloop_a_freq',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_maand_omloop_b_freq',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_week_druk_a1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_week_druk_a2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_week_druk_b1',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_week_druk_b2',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_week_omloop_a_freq',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='gem_week_omloop_b_freq',
        ),
    ]
