# Generated by Django 2.2.6 on 2019-11-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0009_auto_20191107_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gezien', models.BooleanField()),
                ('actief', models.BooleanField()),
                ('score', models.IntegerField()),
                ('assetnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='absolutedata',
            name='storing',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.Storing'),
        ),
    ]
