# Generated by Django 2.2.6 on 2019-11-11 16:29

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0010_auto_20191107_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absolutedata',
            name='storing_beschrijving',
            field=djongo.models.fields.ListField(default=[], editable=False),
        ),
    ]
