# Generated by Django 2.2.7 on 2020-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0011_auto_20200325_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='absolutedata',
            name='alarm_waarde_druk',
            field=models.IntegerField(default=750),
        ),
    ]
