# Generated by Django 2.2.7 on 2019-11-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0011_auto_20191111_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absolutedata',
            name='storing',
        ),
        migrations.AddField(
            model_name='storing',
            name='bericht',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storing',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.AbsoluteData'),
        ),
        migrations.AddField(
            model_name='storing',
            name='som',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='configuratie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.Configuratie'),
        ),
        migrations.AlterField(
            model_name='storing',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
