# Generated by Django 2.2.7 on 2020-04-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0012_absolutedata_alarm_waarde_druk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absolutedata',
            name='alarm_waarde_druk',
        ),
        migrations.AddField(
            model_name='asset',
            name='alarm_waarde_druk_a',
            field=models.IntegerField(default=750),
        ),
        migrations.AddField(
            model_name='asset',
            name='alarm_waarde_druk_b',
            field=models.IntegerField(default=750),
        ),
    ]
