# Generated by Django 2.2.7 on 2019-11-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0012_auto_20191114_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='laatste_data',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tram.LogoData'),
        ),
        migrations.AlterField(
            model_name='storing',
            name='som',
            field=models.IntegerField(default=1),
        ),
    ]
