# Generated by Django 2.2.7 on 2019-11-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0013_auto_20191114_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storing',
            name='data',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.AbsoluteData'),
        ),
    ]
