# Generated by Django 2.2.7 on 2019-11-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0014_auto_20191114_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='logo_online',
            new_name='online',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='bevat_logo',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='laatste_update',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='telefoonnummer',
        ),
    ]
