# Generated by Django 2.2.7 on 2020-05-28 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0015_auto_20200528_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storing',
            name='laatste_data',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tram.AbsoluteData'),
        ),
    ]
