# Generated by Django 2.2.7 on 2019-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0015_auto_20191118_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absolutedata',
            options={'get_latest_by': 'tijdstip', 'verbose_name_plural': 'absolute data'},
        ),
        migrations.AlterModelOptions(
            name='logodata',
            options={'get_latest_by': 'tijdstip', 'verbose_name_plural': 'logo data'},
        ),
        migrations.AlterModelOptions(
            name='storing',
            options={'verbose_name_plural': 'storingen'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='aantal_omlopen',
        ),
        migrations.AlterField(
            model_name='storing',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
