# Generated by Django 2.2.7 on 2020-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0016_auto_20200528_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['assetnummer'], 'permissions': [('toggle_pollbaar_status', 'Kan de pollbaarstatus aanpassen')]},
        ),
    ]
