# Generated by Django 2.2.7 on 2019-11-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0016_auto_20191125_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='laatste_data',
        ),
    ]
