# Generated by Django 2.2.7 on 2019-11-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0017_remove_asset_laatste_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuratieelement',
            name='signaaltype',
        ),
        migrations.RemoveField(
            model_name='storing',
            name='data',
        ),
    ]
