# Generated by Django 2.2.7 on 2019-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0018_auto_20191125_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='storing',
            name='absolute_data',
            field=models.ManyToManyField(editable=False, to='tram.AbsoluteData'),
        ),
    ]
