# Generated by Django 3.0.5 on 2020-07-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0018_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absolutedata',
            options={'get_latest_by': 'tijdstip', 'permissions': [('dashboard_access', 'Heeft toegang tot het dasboard')], 'verbose_name': 'data', 'verbose_name_plural': 'data'},
        ),
    ]
