# Generated by Django 2.2.7 on 2020-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0019_auto_20200727_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='omloop_c',
            field=models.IntegerField(blank=True, default=0, help_text='Het aantal omlopen van de C-bak deze asset.'),
        ),
    ]
