# Generated by Django 2.2.7 on 2019-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0019_storing_absolute_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storing',
            name='absolute_data',
        ),
        migrations.AddField(
            model_name='storing',
            name='data',
            field=models.ManyToManyField(editable=False, to='tram.AbsoluteData'),
        ),
    ]
