# Generated by Django 2.2.7 on 2019-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0020_auto_20191125_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='storing',
            name='laatste_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
