# Generated by Django 2.2.7 on 2019-11-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0021_storing_laatste_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storing',
            name='data',
        ),
    ]
