# Generated by Django 2.2.10 on 2022-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0021_remove_asset_omloop_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='alarm_onder_druk_a',
            field=models.IntegerField(default=750, help_text="Geef hier onderwaarde op die het 'Onderdruk'-alarm triggert voor de A-bak"),
        ),
        migrations.AddField(
            model_name='asset',
            name='alarm_onder_druk_b',
            field=models.IntegerField(default=750, help_text="Geef hier onderwaarde op die het 'Onderdruk'-alarm triggert voor de A-bak"),
        ),
    ]
