# Generated by Django 2.2.7 on 2019-11-26 10:52

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0022_remove_storing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='storing',
            name='data',
            field=djongo.models.fields.ArrayReferenceField(default=None, editable=False, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='tram.AbsoluteData'),
        ),
    ]
