# Generated by Django 2.2.7 on 2019-11-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0023_storing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storing',
            name='data',
        ),
        migrations.RemoveField(
            model_name='storing',
            name='laatste_update',
        ),
        migrations.AddField(
            model_name='storing',
            name='laatste_data',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tram.AbsoluteData'),
        ),
    ]
