# Generated by Django 2.2.7 on 2019-12-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0024_auto_20191126_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLaatsteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetnummer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tram.Asset')),
                ('laatste_data', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tram.AbsoluteData')),
            ],
        ),
    ]
