# Generated by Django 2.2.7 on 2019-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0025_assetlaatstedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuratieelement',
            name='timeout',
            field=models.IntegerField(default=24),
        ),
    ]
