# Generated by Django 2.2.10 on 2022-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0025_auto_20220316_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='omloop_c',
            field=models.IntegerField(blank=True, default=0, help_text='Nieuw aangemaakt.'),
        ),
    ]
