# Generated by Django 2.2.7 on 2019-12-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0025_assetlaatstedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlaatstedata',
            name='assetnummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tram.Asset', unique=True),
        ),
        migrations.AlterField(
            model_name='assetlaatstedata',
            name='laatste_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tram.AbsoluteData'),
        ),
    ]
