# Generated by Django 2.2.7 on 2019-12-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0026_configuratieelement_timeout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetLaatsteData',
        ),
    ]
