# Generated by Django 2.2.7 on 2019-12-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0026_auto_20191202_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlaatstedata',
            name='assetnummer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tram.Asset'),
        ),
    ]
