# Generated by Django 2.2.10 on 2022-03-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0026_asset_omloop_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='omloop_c',
        ),
    ]
