# Generated by Django 2.2.7 on 2019-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0027_delete_assetlaatstedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontvangen', models.DateTimeField()),
                ('modem', models.TextField(default='', max_length=10)),
                ('telnummer', models.TextField(max_length=15)),
                ('omschrijving', models.TextField(max_length=100)),
                ('smsc', models.TextField(max_length=15)),
                ('udh', models.BooleanField()),
                ('inputnummer', models.IntegerField()),
                ('status', models.BooleanField()),
                ('alphabet', models.TextField(max_length=15)),
                ('sent', models.DateTimeField()),
                ('sim', models.TextField(max_length=10)),
                ('asset', models.TextField(max_length=5)),
            ],
        ),
    ]
