# Generated by Django 2.2.7 on 2019-12-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0028_smsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsdata',
            name='omschrijving',
        ),
        migrations.AddField(
            model_name='smsdata',
            name='storing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='alphabet',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='asset',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='inputnummer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='modem',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='sim',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='smsc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='telnummer',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
