# Generated by Django 2.2.7 on 2020-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0029_auto_20191219_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsdata',
            options={'get_latest_by': 'ontvangen', 'verbose_name_plural': 'sms data'},
        ),
        migrations.AlterField(
            model_name='configuratieelement',
            name='beschrijving',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logodata',
            name='omloop_a',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='logodata',
            name='omloop_b',
            field=models.BigIntegerField(),
        ),
    ]
