# Generated by Django 2.2.7 on 2020-02-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0030_auto_20200206_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='ip_adres',
            new_name='ip_adres_logo',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='online',
            new_name='pollbaar',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disconnections',
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_adres_modem',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
