# Generated by Django 2.2.7 on 2020-02-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0031_auto_20200212_1053'),
        ('tram', '0002_auto_20200218_1200'),
    ]

    operations = [
    ]
