# Generated by Django 2.2.7 on 2020-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0031_auto_20200212_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip_adres_logo',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip_adres_modem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
