# Generated by Django 2.2.7 on 2020-03-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0032_auto_20200224_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='gem_dag_druk_a1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_dag_druk_a2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_dag_druk_b1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_dag_druk_b2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_dag_omloop_a_freq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_dag_omloop_b_freq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_maand_druk_a1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_maand_druk_a2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_maand_druk_b1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_maand_druk_b2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_maand_omloop_a_freq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_maand_omloop_b_freq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_week_druk_a1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_week_druk_a2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_week_druk_b1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_week_druk_b2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_week_omloop_a_freq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='gem_week_omloop_b_freq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
