# Generated by Django 2.2.7 on 2020-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0032_merge_20200218_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='lat_coordinaat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='link_fotos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='link_tekeningen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lon_coordinaat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='variant',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip_adres_logo',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ip_adres_modem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
