# Generated by Django 2.2.7 on 2020-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0033_auto_20200218_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lat_coordinaat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='link_fotos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='link_tekeningen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lon_coordinaat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='variant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
